import { timestamp, uuid } from 'drizzle-orm/pg-core';

/** uuid primary key, generated by Postgres. */
export const id = () => uuid('id').primaryKey().defaultRandom();

export const createdAt = () => timestamp('created_at', { withTimezone: true }).notNull().defaultNow();

export const updatedAt = () =>
  timestamp('updated_at', { withTimezone: true })
    .notNull()
    .defaultNow()
    .$onUpdate(() => new Date());

export const timestamps = () => ({ createdAt: createdAt(), updatedAt: updatedAt() });
